package com.example.demo.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.user
 */
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.creatd_at
     *
     * @mbg.generated
     */
    private Date creatdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.id
     *
     * @return the value of public.user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.id
     *
     * @param id the value for public.user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.username
     *
     * @return the value of public.user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.username
     *
     * @param username the value for public.user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.password
     *
     * @return the value of public.user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.password
     *
     * @param password the value for public.user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.creatd_at
     *
     * @return the value of public.user.creatd_at
     *
     * @mbg.generated
     */
    public Date getCreatdAt() {
        return creatdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.creatd_at
     *
     * @param creatdAt the value for public.user.creatd_at
     *
     * @mbg.generated
     */
    public void setCreatdAt(Date creatdAt) {
        this.creatdAt = creatdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.updated_at
     *
     * @return the value of public.user.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.updated_at
     *
     * @param updatedAt the value for public.user.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.token
     *
     * @return the value of public.user.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.token
     *
     * @param token the value for public.user.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}